// demo.js

// Statische Demo-Daten, die exakt der Supabase-Struktur entsprechen
const DEMO_FLIGHTS = [
  {
    id: 9901,
    flight_date: "2024-03-10",
    flight_number: "LH400",
    airline_name: "Lufthansa",
    aircraft_type: "Boeing 747-8",
    dep_code: "FRA",
    dep_name: "Frankfurt am Main",
    dep_lat: 50.0333,
    dep_lon: 8.5706,
    arr_code: "JFK",
    arr_name: "New York JFK",
    arr_lat: 40.6397,
    arr_lon: -73.7789,
    distance_km: 6200,
    duration_minutes: 510,
    seat_number: "1A",
    flight_class: "First",
    registration: "D-ABYA",
    comment: "Start der Weltreise! Fantastischer Service im Oberdeck."
  },
  {
    id: 9902,
    flight_date: "2024-03-15",
    flight_number: "UA1543",
    airline_name: "United Airlines",
    aircraft_type: "Boeing 737 MAX 9",
    dep_code: "JFK",
    dep_name: "New York JFK",
    dep_lat: 40.6397,
    dep_lon: -73.7789,
    arr_code: "SFO",
    arr_name: "San Francisco",
    arr_lat: 37.6188,
    arr_lon: -122.375,
    distance_km: 4150,
    duration_minutes: 385,
    seat_number: "22F",
    flight_class: "Economy",
    registration: "N37532",
    comment: "Transkontinentalflug. Tolle Aussicht über die Rockies."
  },
  {
    id: 9903,
    flight_date: "2024-03-20",
    flight_number: "SQ31",
    airline_name: "Singapore Airlines",
    aircraft_type: "Airbus A350-900ULR",
    dep_code: "SFO",
    dep_name: "San Francisco",
    dep_lat: 37.6188,
    dep_lon: -122.375,
    arr_code: "SIN",
    arr_name: "Singapore Changi",
    arr_lat: 1.3644,
    arr_lon: 103.991,
    distance_km: 13600,
    duration_minutes: 1030,
    seat_number: "12K",
    flight_class: "Business",
    registration: "9V-SGB",
    comment: "Einer der längsten Flüge der Welt!"
  },
  {
    id: 9904,
    flight_date: "2024-03-25",
    flight_number: "EK405",
    airline_name: "Emirates",
    aircraft_type: "Airbus A380-800",
    dep_code: "SIN",
    dep_name: "Singapore Changi",
    dep_lat: 1.3644,
    dep_lon: 103.991,
    arr_code: "DXB",
    arr_name: "Dubai Intl",
    arr_lat: 25.2532,
    arr_lon: 55.3657,
    distance_km: 5850,
    duration_minutes: 440,
    seat_number: "45K",
    flight_class: "Economy",
    registration: "A6-EEO",
    comment: "Zwischenstopp in der Wüste."
  },
  {
    id: 9905,
    flight_date: "2024-03-28",
    flight_number: "LH631",
    airline_name: "Lufthansa",
    aircraft_type: "Airbus A330-300",
    dep_code: "DXB",
    dep_name: "Dubai Intl",
    dep_lat: 25.2532,
    dep_lon: 55.3657,
    arr_code: "FRA",
    arr_name: "Frankfurt am Main",
    arr_lat: 50.0333,
    arr_lon: 8.5706,
    distance_km: 4850,
    duration_minutes: 405,
    seat_number: "14A",
    flight_class: "Premium Eco",
    registration: "D-AIKO",
    comment: "Zurück zu Hause. Reise beendet."
  }
];